name: Sync and Rewrite Authors

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v2
        with:
          repository: MinhOmega/awesome-react-native-ui
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - name: Fetch all branches from source repository
        run: |
          git remote add source https://github.com/minhomega/awesome-react-native-ui.git
          git fetch source --prune

      - name: Rewrite authors for all branches
        run: |
          for branch in $(git branch -r | grep source | grep -v '\->' | sed 's/source\///'); do
            if [ "$branch" = "main" ]; then
              git checkout main
              git reset --hard source/main
            else
              git checkout -b $branch source/$branch || git checkout $branch
              git filter-branch --env-filter '
              CORRECT_NAME="MinhOmega"
              CORRECT_EMAIL="quang.minh@snaptec.co"

              if [ "$GIT_COMMITTER_EMAIL" != "$CORRECT_EMAIL" ]; then
                export GIT_COMMITTER_NAME="$CORRECT_NAME"
                export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
              fi
              if [ "$GIT_AUTHOR_EMAIL" != "$CORRECT_EMAIL" ]; then
                export GIT_AUTHOR_NAME="$CORRECT_NAME"
                export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
              fi
            ' --msg-filter '
              sed "/Co-authored-by:/d"
            ' -f --tag-name-filter cat -- --branches --tags
            fi
          done

      - name: Push all branches to target repository except main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/MinhOmega/awesome-react-native-ui
          for branch in $(git branch -r | grep source | grep -v '\->' | sed 's/source\///'); do
            if [ "$branch" != "main" ]; then
              git checkout $branch
              git push origin $branch --force
            fi
          done

      - name: Push all tags to target repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin --tags --force
